version: 2.0
jobs:
  simple-test:
    docker:
      - image: debian@sha256:de3eac83cd481c04c5d6c7344cd7327625a1d8b2540e82a8231b5675cef0ae5f
    steps:
      - checkout
      - run:
          name: Install stack.
          command: |
            apt-get install curl
            curl -sSL https://get.haskellstack.org/ | sh
      - run:
          name: Run tests.
          command: |
            cd project
            stack test

workflows:
  version: 2
  simple-workflow:
    jobs:
      - simple-test
