version: 2.0
jobs:
  simple-test:
    docker:
      - image: alleledev/debian-haskell
    steps:
      - restore_cache:
          keys:
            - stack-deps
      - checkout
      - run:
          name: Run tests.
          command: |
            set -e
            stack setup
            stack test
      - save_cache:
          key: stack-deps
          paths:
            - .stack
            - ~/.stack


workflows:
  version: 2
  simple-workflow:
    jobs:
      - simple-test
