version: 2.0

jobs:
  simple-test:
    docker:
      - image: alleledev/debian-haskell
    steps:
      - *restore_stack_cache
      - checkout
      - run:
          name: stack test simple-spec
          command: |
            set -e
            stack --no-terminal test citest:simple-spec
      - *save_stack_cache

  involved-test:
    docker:
      - image: alleledev/debian-haskell
    steps:
      - *restore_stack_cache
      - checkout
      - run:
          name: stack test involved-spec
          command: |
            set -e
            stack --no-terminal test citest:involved-spec
      - *save_stack_cache

  perf-test:
    docker:
      - image: alleledev/debian-haskell
    steps:
      - *restore_stack_cache
      - checkout
      - run:
          name: stack bench
          command: |
            set -e
            stack --no-terminal bench
      - *save_stack_cache



workflows:
  version: 2
  simple-workflow:
    jobs:
      - simple-test
      - perf-test

  once-an-hour-workflow:
    triggers:
      - schedule:
          cron: "15 * * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - involved-test

references:

  restore_stack_cache:
    - restore_cache:
        keys:
          - stack-deps

  save_stack_cache:
    - save_cache:
        key: stack-deps
        paths:
          - .stack
          - ~/.stack
