version: 2.0
jobs:
  simple-test:
    docker:
      - image: alleledev/debian-haskell
    steps:
      - checkout
      - run:
          name: Run tests.
          command: |
            ls
            stack test

workflows:
  version: 2
  simple-workflow:
    jobs:
      - simple-test
